import { test, expect } from "@playwright/test";

test("V2 refund, shift carry and editors work across viewport sizes", async ({ page, context, baseURL }, info) => {
  test.skip(process.env.APP_ENV !== "test" || !process.env.V2_E2E_TOKEN || !process.env.V2_E2E_BRANCHES || !process.env.V2_E2E_PRODUCT, "Requires explicitly isolated V2 fixture environment");
  expect(new URL(baseURL!).hostname).toBe("127.0.0.1");
  await context.addCookies([{ name: "pharmacy_erp_auth", value: process.env.V2_E2E_TOKEN!, url: baseURL!, httpOnly: true, sameSite: "Lax" }]);
  page.setDefaultTimeout(10000);
  const branch = JSON.parse(process.env.V2_E2E_BRANCHES!)[info.project.name] as string;
  const product = process.env.V2_E2E_PRODUCT!;
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  const command = async (path: string, body: Record<string, unknown>) => {
    const response = await page.request.post(`/api/v2${path}`, { data: { ...body, branch_id: branch }, headers: { "Idempotency-Key": crypto.randomUUID() } });
    expect(response.status(), `${path}: ${await response.text()}`).toBe(200);
    return response.json();
  };
  await command("/policy", { cost_method: "fifo", allow_branch_promotions: true, max_discount_bps: 1000 });
  const customer = (await command("/customers", { code: crypto.randomUUID(), type: "person", name: "V2 browser customer", active: true, credit_limit_cents: 1_000_000 })).id;
  await command("/stock/receive", { reference: "browser fixture", items: [{ product_id: product, quantity: 10, unit_cost_cents: 100, lot_number: "BROWSER", expires_on: "2099-12-31" }] });
  const invoice = await command("/documents", { kind: "ar_invoice", customer_id: customer, lines: [{ product_id: product, quantity: 1, vat_bps: 700 }] });
  await command("/payments", { direction: "receive", customer_id: customer, method: "bank_transfer", amount_cents: 10700, allocations: [{ document_id: invoice.id, amount_cents: 10700 }] });
  await page.goto("/v2");
  await expect(page.getByRole("heading", { name: "พื้นที่ V2", exact: true })).toBeVisible();
  await page.getByLabel("สาขา", { exact: true }).selectOption(branch);
  const tab = async (name: string) => {
    const target = page.getByRole("navigation", { name: "งาน V2" }).getByRole("button", { name, exact: true });
    const loaded = page.waitForResponse((r) => r.url().includes("/api/v2/catalog?") && r.request().method() === "GET");
    await target.scrollIntoViewIfNeeded(); await target.click(); await loaded;
    await expect(page.getByText("กำลังโหลดข้อมูล…", { exact: true })).not.toBeVisible();
    await expect(page.getByRole("alert").filter({ hasText: "ไม่สำเร็จ" })).toHaveCount(0);
  };
  const clickSave = async (name: string, path: string) => {
    const response = page.waitForResponse((r) => r.url().includes(`/api/v2${path}`) && r.request().method() === "POST");
    await page.getByRole("button", { name, exact: true }).click(); expect((await response).status()).toBe(200);
    await expect(page.getByText("กำลังบันทึก…", { exact: true })).not.toBeVisible();
  };
  await tab("เอกสาร");
  await page.getByRole("button", { name: "รายละเอียด", exact: true }).click();
  await page.getByText("ยกเลิกบิลและจัดการคืนลูกค้า", { exact: true }).click();
  await page.getByLabel("อ้างอิงการยกเลิก", { exact: true }).fill("browser cancel");
  await page.getByLabel("เหตุผลยกเลิก", { exact: true }).fill("customer cancellation");
  await page.getByLabel("ได้รับสินค้าทั้งหมดคืนแล้ว ให้รับส่วนที่ยังไม่คืนเข้ากักกัน", { exact: true }).check();
  await page.getByLabel("ยืนยันยกเลิกบิลและรับผิดชอบยอดรอคืน", { exact: true }).check();
  await clickSave("ยกเลิกบิล", "/documents/cancel");
  await tab("คืนบิลที่ยกเลิก");
  await page.getByRole("combobox", { name: "วิธีคืน", exact: true }).selectOption("goods");
  await page.getByLabel("หลักฐาน/อ้างอิง", { exact: true }).fill("browser exchange");
  await page.getByLabel("เหตุผล", { exact: true }).fill("equivalent goods");
  await page.getByRole("combobox", { name: "สินค้า", exact: true }).selectOption(product);
  await page.getByLabel("ยืนยันว่าลูกค้าได้รับเงินหรือสินค้าแล้ว", { exact: true }).check();
  await clickSave("บันทึกการคืน", "/refunds");
  await expect(page.getByText("คืนครบแล้ว", { exact: true })).toBeVisible();
  const nextInvoice = await command("/documents", { kind: "ar_invoice", customer_id: customer, lines: [{ product_id: product, quantity: 1 }] });
  await command("/payments", { direction: "receive", customer_id: customer, method: "bank_transfer", amount_cents: 10000, allocations: [{ document_id: nextInvoice.id, amount_cents: 10000 }] });
  const pending = await command("/documents/cancel", { document_id: nextInvoice.id, reason: "carry refund", reference: "carry" });
  await tab("รอบเงินสด");
  await expect(page.getByRole("heading", { name: "รายการค้างที่ต้องรับทราบก่อนปิดกะ" })).toBeVisible();
  await clickSave("เปิดรอบเงินสด", "/drawers");
  await page.getByLabel("ยอดนับจริง (บาท)", { exact: true }).fill("0");
  await page.getByLabel("รับทราบรายการค้างทั้งหมด และส่งต่อกะใหม่", { exact: true }).check();
  await clickSave("ปิดรอบเงินสด", "/drawers/close");
  await clickSave("เปิดรอบเงินสด", "/drawers");
  await expect(page.getByRole("heading", { name: "รายการค้างที่ต้องรับทราบก่อนปิดกะ" })).toBeVisible();
  await command("/refunds", { cancellation_id: pending.id, method: "bank_transfer", amount_cents: 10000, reference: "carry settled", reason: "bank refund" });
  await tab("สต๊อก"); await tab("รอบเงินสด");
  await expect(page.getByRole("heading", { name: "รายการค้างที่ต้องรับทราบก่อนปิดกะ" })).toHaveCount(0);
  await page.getByLabel("ยอดนับจริง (บาท)", { exact: true }).fill("0");
  await clickSave("ปิดรอบเงินสด", "/drawers/close");
  await tab("โอนระหว่างทาง");
  await page.getByRole("button", { name: "+ เพิ่มรายการ", exact: true }).click();
  await expect(page.getByRole("group")).toHaveCount(2);
  const destination = JSON.parse(process.env.V2_E2E_BRANCHES!)[info.project.name === "desktop" ? "tablet" : "desktop"] as string;
  const policy = await page.request.post("/api/v2/policy", { data: { branch_id: destination, cost_method: "fifo", allow_branch_promotions: true, max_discount_bps: 1000 }, headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(policy.status()).toBe(200);
  await page.getByLabel("สาขาปลายทาง", { exact: true }).selectOption(destination);
  await page.getByLabel("เอกสารอ้างอิง", { exact: true }).fill("browser multiline transfer");
  for (const group of await page.getByRole("group").all()) await group.getByRole("combobox", { name: "สินค้า", exact: true }).selectOption(product);
  await clickSave("จ่ายต้นทางเข้าระหว่างทาง", "/shipments");
  await expect(page.getByText("browser multiline transfer · dispatched", { exact: true })).toBeVisible();
  await tab("โปรโมชั่น");
  await expect(page.getByRole("combobox", { name: "ขอบเขต", exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "ประเภท", exact: true }).selectOption("buy_x_get_y");
  await expect(page.getByRole("group", { name: "สินค้าแถม", exact: true })).toBeVisible();
  await command("/promotions", { scope: "branch", code: crypto.randomUUID(), name: "Browser promotion", type: "percent", starts_on: "2020-01-01", active: true, reason: "browser fixture", rule: { discount_bps: 1000 } });
  await tab("สต๊อก"); await tab("โปรโมชั่น");
  const promoCard = page.locator("details").filter({ hasText: "Browser promotion" });
  await promoCard.locator("summary").click();
  await promoCard.getByLabel("ลด (%)", { exact: true }).fill("20");
  await promoCard.getByLabel("เหตุผลกำหนด/แก้ไขโปร", { exact: true }).fill("browser edits promotion");
  await clickSave("บันทึกแก้ไขโปรโมชั่น", "/promotions");
  await expect(page.locator("details").filter({ hasText: "Browser promotion" }).locator("summary")).toContainText("รุ่น 2");
  const quote = await command("/documents", { kind: "quotation", customer_id: customer, lines: [{ product_id: product, quantity: 1 }] });
  await tab("เอกสาร");
  const card = page.locator("article").filter({ hasText: quote.document_number });
  await card.getByRole("button", { name: "รายละเอียด", exact: true }).click();
  await page.getByRole("button", { name: "แก้ใบเสนอราคา/สร้าง revision", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "ลูกค้า", exact: true }).last()).toBeVisible();
  await page.getByRole("button", { name: "+ เพิ่มรายการ", exact: true }).last().click();
  await expect(page.getByText("รายการ 2", { exact: true }).last()).toBeVisible();
  await page.getByRole("combobox", { name: "สินค้า", exact: true }).last().selectOption(product);
  await page.getByLabel("เหตุผล revision", { exact: true }).fill("browser adds quote line");
  await page.getByLabel("ตรวจรายการ ส่วนลด และโปรโมชั่นของฉบับใหม่แล้ว", { exact: true }).check();
  await clickSave("บันทึก revision", "/quotations/revise");
  await expect(page.locator("article").filter({ hasText: quote.document_number })).toContainText("cancelled");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await page.goto("/sales-management");
  await expect(page.getByRole("link", { name: "เปิดใบเสนอราคาและใบขาย V2" })).toBeVisible();
  await expect(page.getByText("ใบเสนอราคาและใบขาย ยังไม่เปิดใช้งาน")).toHaveCount(0);
  await page.goto("/government-sales");
  await expect(page.getByText("งานส่วนนี้อยู่ในแผนพัฒนาลำดับถัดไป ยังไม่พร้อมทำรายการ")).toBeVisible();
});
